spring:
  application:
    name: iamlook-provider
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adeep?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置初始化大小、最小、最大
    maxActive: 20
    initialSize: 1
    minIdle: 1
    # 配置监控统计拦截的filters
    filters: stat
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验语句
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: -1
      # 连接池中的最大空闲连接
      max-wait: 8
      # 连接池中的最小空闲连接
      min-idle: 0



server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8
#指定当前服务/应用的名字（同样的服务名字相同，不要和别的服务同名）
dubbo:
  application:
    name: iamlook-provider
  protocol:
    name: dubbo
    port: 20880
  #指定注册中心的位置
  registry:
    address: zookeeper://localhost:2181
  #统一设置服务提供方的规则
  provider:
    timeout: 1000
  scan:
    base-packages: com.iamlook.um.service.impl

# 实体扫描，多个package用逗号或者分号分隔
mybatis-plus:
  type-aliases-package: com.iamlook.entity
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    # 主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    # 字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    meta-object-handler: com.iamlook.um.config.AutoMetaObjectHandler
  configuration:
    # 开启查询结果下划线转驼峰
    map-underscore-to-camel-case: true
    cache-enabled: false












